# Generates a clang config file per machine. Users consume it as:
#
#   mos-clang --config=$PICOMOS/share/picomos/configs/picomos-<machine>.cfg \
#             main.c -o hello.elf
#
# Clang config files are documented at
# https://clang.llvm.org/docs/UsersManual.html#configuration-files —
# they are simply lists of command-line arguments, one group per line.
#
# The config file sets up the sysroot, points at the picolibc libs, and
# pulls in the machine's crt0, linker script, and I/O archive.
#
# Paths are recorded RELATIVE TO THE CONFIG FILE using the
# <CFGDIR> macro that clang expands, so the SDK is relocatable — users
# can install it anywhere.

function(picomos_write_config machine_name)
    cmake_parse_arguments(PARSE_ARGV 1 CFG
        "" "HAS_LINK;HAS_CRT0;HAS_IO" "LINK_LIBS")

    # Staged path (build-tree consumers) and installed path (final SDK).
    set(_staged_cfg  "${CMAKE_BINARY_DIR}/staging/share/picomos/configs/picomos-${machine_name}.cfg")
    file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/staging/share/picomos/configs")

    # Compute how many "../" it takes to get from the config file's dir
    # to the sysroot. Config lives at:
    #   <prefix>/share/picomos/configs/picomos-<mach>.cfg
    # Sysroot lives at:
    #   <prefix>/mos-elf
    # So relative to <CFGDIR>, the sysroot is: ../../../mos-elf
    set(_sysroot_rel "../../../mos-elf")
    set(_machine_rel "${_sysroot_rel}/usr/share/picomos/machines/${machine_name}")

    # Assemble config file contents.
    set(_lines "")
    list(APPEND _lines "# picomos-${machine_name}.cfg — generated by picomos, do not edit.")
    list(APPEND _lines "# Consumed as: mos-clang --config=<this-file> foo.c -o foo.elf")
    list(APPEND _lines "")
    list(APPEND _lines "# picolibc-for-MOS architectural defaults. Required by")
    list(APPEND _lines "# machine/ieeefp.h and long-double handling in picolibc headers.")
    list(APPEND _lines "-D__IEEE_LITTLE_ENDIAN")
    list(APPEND _lines "-D_LDBL_EQ_DBL")
    list(APPEND _lines "")
    list(APPEND _lines "--sysroot=<CFGDIR>/${_sysroot_rel}")
    list(APPEND _lines "-isystem <CFGDIR>/${_sysroot_rel}/usr/include")

    # Machine overlay `-L` comes FIRST so llvm-mos's clang driver, which
    # unconditionally appends `-Tlink.ld` to every link, resolves that
    # to THIS machine's link.ld (multi-machine safe — each machine
    # ships its own script under its own subdir). Emitting an explicit
    # -T here would cause a duplicate INCLUDE and "region already
    # defined" errors.
    list(APPEND _lines "-L<CFGDIR>/${_machine_rel}")
    list(APPEND _lines "-L<CFGDIR>/${_sysroot_rel}/usr/lib")
    list(APPEND _lines "")
    list(APPEND _lines "# Bypass llvm-mos's built-in platform defaults (libcrt, link.ld) —")
    list(APPEND _lines "# picomos supplies its own startup and linker script via the machine overlay.")
    list(APPEND _lines "-nostdlib")
    list(APPEND _lines "")
    if(CFG_HAS_CRT0)
        list(APPEND _lines "# Machine startup / auxiliary link inputs")
        list(APPEND _lines "<CFGDIR>/${_machine_rel}/crt0.o")
    endif()
    list(APPEND _lines "")
    list(APPEND _lines "# picolibc is always present. The picolibc-provided crt0 archive")
    list(APPEND _lines "# (libcrt0-*.a) and any machine-specific libraries are pulled in")
    list(APPEND _lines "# via GROUP() inside the machine's linker script or via LINK_LIBS below.")
    list(APPEND _lines "-lc")
    foreach(_lib IN LISTS CFG_LINK_LIBS)
        list(APPEND _lines "${_lib}")
    endforeach()
    if(CFG_HAS_IO)
        list(APPEND _lines "-lio")
    endif()

    string(REPLACE ";" "\n" _body "${_lines}")
    file(WRITE "${_staged_cfg}" "${_body}\n")

    install(FILES "${_staged_cfg}"
            DESTINATION share/picomos/configs)
endfunction()
